spring:
  application:
    name: dpgb
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}

book-service:
  security:
    cognito:
      app-client-id: ${AUTH_APP_CLIENT_ID}
  aladin:
    ttb-key: ${ALADIN_API_TTB_KEY}
